const sampleListings = [
  // ──────────────────────────── INDIA DESTINATIONS ────────────────────────────
  {
    title: "Aura Oceanfront Luxury Villa & Private Pool",
    description:
      "Perched right on the cliffs overlooking the Arabian Sea in North Goa. Enjoy sweeping ocean sunsets, a private infinity plunge pool, lush tropical garden, open-air sun deck, and direct private trail to pristine beaches.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 6800,
    location: "Vagator, Goa",
    country: "India",
    category: "Beach",
    geometry: { lat: 15.5997, lng: 73.7431 },
    amenities: ["Beach Access", "Private Pool", "High-speed Wifi", "Air Conditioning", "Free Parking", "Kitchen", "Chef on Request"],
    rating: 4.96,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 3,
    aiSummary: {
      positives: ["Stunning direct sunset sea views", "Spotless private plunge pool", "Exceptional hospitality & local seafood"],
      negatives: ["Clifftop path requires careful walking at night"],
      overall: "A postcard-perfect Goan coastal getaway with luxurious amenities and tranquil sunsets.",
      sentiment: 96,
      updatedAt: new Date(),
    },
  },
  {
    title: "Cedar Peaks Alpine Chalet & Stone Fireplace",
    description:
      "Handcrafted from Himalayan deodar cedar and local river stone, this secluded alpine chalet overlooks snow-dusted pine forests and the roaring Beas valley in Old Manali. Features a cozy wood-burning hearth and a panoramic attic stargazing balcony.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 4200,
    location: "Old Manali, Himachal Pradesh",
    country: "India",
    category: "Mountains",
    geometry: { lat: 32.2530, lng: 77.1750 },
    amenities: ["Mountain View", "Indoor Fireplace", "High-speed Wifi", "Room Heater", "Balcony", "Free Breakfast", "Bonfire Pit"],
    rating: 4.92,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    aiSummary: {
      positives: ["Breathtaking mountain & pine forest vistas", "Warm cedar wood ambiance", "Cozy indoor fireplace"],
      negatives: ["Winter road can get slippery during heavy snowfall"],
      overall: "The quintessential mountain escape in Manali with comforting warmth and postcard views.",
      sentiment: 94,
      updatedAt: new Date(),
    },
  },
  {
    title: "The Royal Heritage Haveli & Marble Courtyard",
    description:
      "Step into timeless Rajasthani royalty inside a meticulously restored 19th-century haveli in the Pink City. Features intricate hand-carved jharokha balconies, frescoed high ceilings, peaceful fountain courtyard, and rooftop views of Nahargarh Fort.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1599661046289-e31897846e41?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 5400,
    location: "Pink City, Jaipur, Rajasthan",
    country: "India",
    category: "Historical",
    geometry: { lat: 26.9239, lng: 75.8267 },
    amenities: ["Courtyard Fountain", "Rooftop Dining", "Air Conditioning", "Heritage Decor", "High-speed Wifi", "Free Parking"],
    rating: 4.89,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    aiSummary: {
      positives: ["Authentic regal Rajasthani architecture", "Delicious rooftop dining", "Centrally located near Hawa Mahal"],
      negatives: ["Old city lanes are lively and can be busy during festivals"],
      overall: "An unforgettable cultural immersion with royal comforts and authentic architecture.",
      sentiment: 92,
      updatedAt: new Date(),
    },
  },
  {
    title: "Lake Pichola Palace View Boutique Suite",
    description:
      "Wake up to the golden waters of Lake Pichola and unobstructed views of Udaipur City Palace. Featuring hand-carved scalloped arches, antique brass details, private candlelit terrace, and personalized breakfast service.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 8900,
    location: "Udaipur, Rajasthan",
    country: "India",
    category: "Castle",
    geometry: { lat: 24.5764, lng: 73.6835 },
    amenities: ["Lake View", "Private Terrace", "Butler Service", "Air Conditioning", "High-speed Wifi", "Breakfast Included"],
    rating: 4.97,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    aiSummary: {
      positives: ["Mesmerizing lakefront panoramic views", "Impeccable personalized service", "Superb romantic ambiance"],
      negatives: ["Steps leading up to terrace"],
      overall: "A top-tier romantic stay in the City of Lakes with unmatched scenic panoramas.",
      sentiment: 98,
      updatedAt: new Date(),
    },
  },
  {
    title: "Misty Tea Plantation Colonial Bungalow",
    description:
      "Surrounded by emerald rolling tea estates and refreshing mountain mist in Munnar. This vintage British colonial-era bungalow offers stone fireplaces, private tea garden walking trails, and traditional Kerala culinary delights.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 3800,
    location: "Munnar, Kerala",
    country: "India",
    category: "Countryside",
    geometry: { lat: 10.0889, lng: 77.0595 },
    amenities: ["Tea Estate View", "Indoor Fireplace", "Private Garden", "Bird Watching", "Wifi", "Home Cooked Meals"],
    rating: 4.91,
    guests: 5,
    bedrooms: 3,
    beds: 3,
    baths: 2,
    aiSummary: {
      positives: ["Tranquil tea garden surroundings", "Fresh mountain air & morning fog", "Authentic home-cooked meals"],
      negatives: ["Mobile signal can be patchy; Wifi is steady"],
      overall: "A rejuvenating retreat amidst South India's finest hill estates.",
      sentiment: 93,
      updatedAt: new Date(),
    },
  },
  {
    title: "Serene Backwaters Teakwood Floating Houseboat",
    description:
      "Glide gently across the emerald waters of Alleppey in this handcrafted air-conditioned kettuvallam houseboat. Boasts an open upper sun deck, dedicated captain, private chef serving fresh pearl spot fish, and peaceful overnight docking under starry skies.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 7200,
    location: "Alleppey, Kerala",
    country: "India",
    category: "Lake",
    geometry: { lat: 9.4981, lng: 76.3388 },
    amenities: ["Waterfront Sundeck", "Private Captain & Chef", "Air Conditioning", "Fresh Catch Dining", "Wifi"],
    rating: 4.94,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    aiSummary: {
      positives: ["Magical backwater cruise experience", "Sumptuous authentic Kerala food", "Very friendly boat crew"],
      negatives: ["Evening mosquitoes outside on deck; coils provided"],
      overall: "An iconic Kerala experience offering serenity and delicious dining on water.",
      sentiment: 95,
      updatedAt: new Date(),
    },
  },
  {
    title: "Ganges Riverside Eco Camp & Yoga Retreat",
    description:
      "Luxury safari canvas tents pitched right beside the crystalline turquoise waters of the upper Ganges in Rishikesh. Includes sunrise guided yoga, evening bonfire circles, and white-water rafting arrangements.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1510312305653-8ed496efae75?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 2900,
    location: "Rishikesh, Uttarakhand",
    country: "India",
    category: "Camping",
    geometry: { lat: 30.1345, lng: 78.3228 },
    amenities: ["Riverfront Access", "Campfire", "Daily Yoga Sessions", "Rafting Gear", "Open-air Dining", "Free Parking"],
    rating: 4.87,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    aiSummary: {
      positives: ["Soothing sound of the river Ganga", "Energizing morning yoga sessions", "Lively campfire ambiance"],
      negatives: ["Eco tents have shared outdoor-style luxury washrooms"],
      overall: "Perfect blend of outdoor adventure and mindfulness by the sacred river.",
      sentiment: 91,
      updatedAt: new Date(),
    },
  },
  {
    title: "Stargazing Geodesic Dome in Nubra Valley",
    description:
      "Sleep beneath the brilliant Milky Way in a heated geodesic glass dome in the Karakoram high desert. Enjoy 360-degree views of sand dunes, snow-capped peaks, and crystal clear night skies with high-powered telescope stargazing.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1517824806704-9040b037703b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 5200,
    location: "Nubra Valley, Ladakh",
    country: "India",
    category: "Adventure",
    geometry: { lat: 34.6939, lng: 77.5619 },
    amenities: ["Telescope Included", "Room Heater", "Mountain View", "Organic Dining", "Free Parking", "Oxygen Cylinder on Request"],
    rating: 4.95,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    aiSummary: {
      positives: ["Incredible night sky & Milky Way views", "Unique heated dome design", "Warm Ladakhi hospitality"],
      negatives: ["Cold desert nights; heaters keep inside cozy"],
      overall: "An otherworldly high-altitude adventure that stargazers will remember forever.",
      sentiment: 96,
      updatedAt: new Date(),
    },
  },
  {
    title: "Colonial Rosewood Villa in the Nilgiri Hills",
    description:
      "Nestled among towering eucalyptus and pine trees in Ooty, this restored heritage villa features Victorian bay windows, private botanical gardens, cozy fireplace living rooms, and vintage high tea service.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1587061949409-02df41d5e562?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 3600,
    location: "Ooty, Tamil Nadu",
    country: "India",
    category: "Forest",
    geometry: { lat: 11.4102, lng: 76.6950 },
    amenities: ["Forest View", "Garden Bonfire", "Indoor Fireplace", "High-speed Wifi", "Free Parking", "Kitchenette"],
    rating: 4.88,
    guests: 5,
    bedrooms: 2,
    beds: 3,
    baths: 2,
    aiSummary: {
      positives: ["Peaceful natural setting", "Warm interior wooden finishes", "Beautiful flowering gardens"],
      negatives: ["Slightly uphill walk from main road"],
      overall: "A peaceful hill station haven steeped in vintage colonial charm.",
      sentiment: 92,
      updatedAt: new Date(),
    },
  },
  {
    title: "Ancient Ghat Heritage Sanctuary on the Ganges",
    description:
      "Immerse yourself in the timeless spiritual aura of Varanasi from this 200-year-old stone residence overlooking historic Dashashwamedh Ghat. Includes private morning sunrise boat tours and rooftop meditation space.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 3100,
    location: "Varanasi, Uttar Pradesh",
    country: "India",
    category: "Historical",
    geometry: { lat: 25.3076, lng: 83.0130 },
    amenities: ["Ghat River View", "Morning Boat Tour", "Rooftop Terrace", "Air Conditioning", "High-speed Wifi"],
    rating: 4.86,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    aiSummary: {
      positives: ["Direct river & Ganga Aarti views from roof", "Deep historic charm", "Helpful host for cultural walks"],
      negatives: ["Narrow pedestrian-only lanes near ghats"],
      overall: "An evocative stay at the sacred heart of one of the world's oldest cities.",
      sentiment: 90,
      updatedAt: new Date(),
    },
  },

  // ──────────────────────────── WORLDWIDE DESTINATIONS ────────────────────────────
  {
    title: "Haussmannian Chic Loft near the Eiffel Tower",
    description:
      "Classic Parisian luxury featuring herringbone oak floors, ornate marble fireplaces, high crown moldings, and wrought-iron balconies with direct views of the Eiffel Tower in the prestigious 7th Arrondissement.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 14500,
    location: "7th Arrondissement, Paris",
    country: "France",
    category: "City",
    geometry: { lat: 48.8584, lng: 2.2945 },
    amenities: ["Eiffel Tower View", "Designer Kitchen", "Elevator", "High-speed Wifi", "Air Conditioning", "Espresso Bar"],
    rating: 4.97,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    aiSummary: {
      positives: ["Iconic Eiffel Tower view from balcony", "Exquisite Parisian interior design", "Steps to gourmet bakeries"],
      negatives: ["Metro noise if balcony doors left wide open"],
      overall: "The quintessential Parisian dream apartment in the heart of the city of lights.",
      sentiment: 97,
      updatedAt: new Date(),
    },
  },
  {
    title: "Cliffside Caldera Cave Suite & Infinity Plunge",
    description:
      "Sculpted into the volcanic cliff face of Oia, this whitewashed Cycladic cave suite boasts a heated infinity plunge pool, private sun lounger terrace with world-renowned Aegean Sea sunsets, and complimentary champagne breakfast.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 18500,
    location: "Oia, Santorini",
    country: "Greece",
    category: "Luxury",
    geometry: { lat: 36.4618, lng: 25.3753 },
    amenities: ["Heated Infinity Pool", "Caldera Sunset View", "Daily Champagne Breakfast", "High-speed Wifi", "Air Conditioning", "Airport Transfer"],
    rating: 4.99,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    aiSummary: {
      positives: ["Unrivaled sunset views over the caldera", "Private heated plunge pool is divine", "Outstanding concierge service"],
      negatives: ["Lots of stairs down the cliff, typical of Oia"],
      overall: "An ultra-romantic, unforgettable Mediterranean experience at the top of the world.",
      sentiment: 99,
      updatedAt: new Date(),
    },
  },
  {
    title: "Matterhorn View Luxury Alpine Ski Chalet",
    description:
      "Ski directly in and out from your private chalet doorstep in Zermatt. Enjoy unhindered vistas of the iconic Matterhorn, private cedar wood sauna, outdoor bubbling hot tub, grand central stone fireplace, and sommelier-curated wine cellar.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 22000,
    location: "Zermatt, Valais",
    country: "Switzerland",
    category: "Mountains",
    geometry: { lat: 45.9765, lng: 7.7491 },
    amenities: ["Ski-in / Ski-out", "Cedar Sauna", "Outdoor Hot Tub", "Matterhorn View", "Fireplace", "High-speed Wifi"],
    rating: 4.98,
    guests: 8,
    bedrooms: 4,
    beds: 5,
    baths: 4,
    aiSummary: {
      positives: ["Clear, unobstructed view of Matterhorn", "Luxury sauna & outdoor spa", "True ski-in / ski-out convenience"],
      negatives: ["Car-free village requires electric taxi from station"],
      overall: "Peak Alpine luxury with world-class amenities and breathtaking mountain vistas.",
      sentiment: 98,
      updatedAt: new Date(),
    },
  },
  {
    title: "Hideaway Bamboo Treehouse & Jungle River Pool",
    description:
      "An architectural masterpiece built entirely of sustainable golden bamboo, suspended high above the sacred Ayung River valley in Ubud. Features open-air loft living, net hammock beds, natural spring plunge pool, and daily organic breakfast.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 8200,
    location: "Ubud, Bali",
    country: "Indonesia",
    category: "Forest",
    geometry: { lat: -8.5069, lng: 115.2625 },
    amenities: ["Jungle Valley View", "Natural River Pool", "Open-air Bath", "Yoga Shala", "Wifi", "Floating Breakfast", "Free Parking"],
    rating: 4.95,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    aiSummary: {
      positives: ["Architectural bamboo work is stunning", "Waking up to sounds of the jungle river", "Floating breakfast experience"],
      negatives: ["Open-air living means you will see harmless tropical insects"],
      overall: "A once-in-a-lifetime tropical sanctuary immersed in lush nature.",
      sentiment: 95,
      updatedAt: new Date(),
    },
  },
  {
    title: "Cliffside Lemon Grove Villa in Positano",
    description:
      "Perched high above the sapphire waters of the Amalfi Coast, surrounded by fragrant terraced lemon groves. Enjoy expansive sea-facing sun terraces, authentic Italian outdoor pizza oven, private cliff trail down to Spiaggia Grande, and sunset aperitifs.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1533105079780-92b9be482077?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 19500,
    location: "Positano, Amalfi Coast",
    country: "Italy",
    category: "Beach",
    geometry: { lat: 40.6281, lng: 14.4850 },
    amenities: ["Sea View Terrace", "Stone Pizza Oven", "Private Trail", "Air Conditioning", "Wifi", "Wine Cellar", "Chef Available"],
    rating: 4.96,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 3,
    aiSummary: {
      positives: ["Panoramic Amalfi coastline vistas", "Homemade pizza oven was a blast", "Spectacular terrace dining"],
      negatives: ["Positano steps require good stamina"],
      overall: "Pure Italian coastal magic with world-class vistas and authentic charm.",
      sentiment: 96,
      updatedAt: new Date(),
    },
  },
  {
    title: "Lake Louise Handcrafted Cedar Log Lodge",
    description:
      "Nestled among towering Douglas firs in Banff National Park, this grand timber lodge offers massive peeled-pine log beams, a colossal fieldstone hearth, radiant heated stone floors, and complimentary wooden canoes on turquoise glacial waters.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 9800,
    location: "Banff National Park, Alberta",
    country: "Canada",
    category: "Lake",
    geometry: { lat: 51.4254, lng: -116.1773 },
    amenities: ["Glacier Lake Access", "Stone Fireplace", "Canoe Included", "Heated Floors", "High-speed Wifi", "Free Parking", "BBQ Grill"],
    rating: 4.93,
    guests: 6,
    bedrooms: 3,
    beds: 4,
    baths: 2,
    aiSummary: {
      positives: ["Magical lake and mountain scenery", "Warm crackling fireplace", "Canoeing directly on glacial waters"],
      negatives: ["Early booking required for national park activities"],
      overall: "A dream Canadian Rockies wilderness haven with supreme comfort.",
      sentiment: 94,
      updatedAt: new Date(),
    },
  },
  {
    title: "120-Year Traditional Zen Machiya & Bamboo Garden",
    description:
      "A meticulously restored historical merchant house in Kyoto's Gion district. Features aromatic tatami rooms, fragrant Japanese Hinoki cypress soaking ofuro tub, hand-painted sliding shoji screens, and a serene private moss-and-bamboo courtyard garden.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 11200,
    location: "Gion District, Kyoto",
    country: "Japan",
    category: "Historical",
    geometry: { lat: 35.0037, lng: 135.7772 },
    amenities: ["Hinoki Cypress Tub", "Private Zen Garden", "Tatami Rooms", "Tea Ceremony Set", "High-speed Wifi", "Floor Heating"],
    rating: 4.97,
    guests: 4,
    bedrooms: 2,
    beds: 4,
    baths: 1,
    aiSummary: {
      positives: ["Deep cultural immersion & peacefulness", "The cedar ofuro bath is heavenly", "Convenient location in historic Gion"],
      negatives: ["Traditional wooden structure requires quiet voice at night"],
      overall: "An exceptional and authentic slice of Japanese history and craftsmanship.",
      sentiment: 97,
      updatedAt: new Date(),
    },
  },
  {
    title: "Royal Desert Dune Oasis & Starlight Pool",
    description:
      "Ultra-luxurious Bedouin-inspired desert oasis nestled among the rolling golden dunes of Dubai. Features a private temperature-controlled infinity pool overlooking desert horizons, evening falconry demonstrations, and private majlis starlight dining.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 16000,
    location: "Al Marmoom, Dubai",
    country: "United Arab Emirates",
    category: "Desert",
    geometry: { lat: 24.8322, lng: 55.4517 },
    amenities: ["Private Dune Pool", "Desert Safari Included", "Stargazing Lounge", "Air Conditioning", "Butler Service", "Wifi"],
    rating: 4.95,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    aiSummary: {
      positives: ["Unmatched desert tranquility & privacy", "Private pool surrounded by golden sand", "Five-star Arabian hospitality"],
      negatives: ["Located 40 minutes outside downtown Dubai"],
      overall: "A lavish Arabian nights fantasy come to life with supreme modern luxury.",
      sentiment: 95,
      updatedAt: new Date(),
    },
  },
  {
    title: "Aurora Borealis Heated Glass Dome Retreat",
    description:
      "Gaze at the dancing Northern Lights from your custom heated king bed inside an insulated panoramic glass igloo on Iceland's Golden Circle. Features private geothermal outdoor hot tub and reindeer fur throw blankets.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 13500,
    location: "Golden Circle, Reykjavik",
    country: "Iceland",
    category: "Arctic",
    geometry: { lat: 64.1466, lng: -21.9426 },
    amenities: ["Aurora Viewing Glass", "Geothermal Hot Tub", "Heated King Bed", "Mountain View", "High-speed Wifi", "Breakfast Basket"],
    rating: 4.98,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    aiSummary: {
      positives: ["Saw the northern lights from bed!", "Soaking in geothermal tub in crisp air", "Super cozy and heated interior"],
      negatives: ["Weather dependent for aurora sightings"],
      overall: "A bucket-list Arctic experience that exceeds every expectation.",
      sentiment: 98,
      updatedAt: new Date(),
    },
  },
  {
    title: "Alpine Lake Wakatipu Glass Sanctuary",
    description:
      "Perched right above crystal Lake Wakatipu with jaw-dropping views of The Remarkables mountain range in Queenstown. Features an outdoor sunken cedar hot tub, indoor open hearth, drying room for ski gear, and floor-to-ceiling glass walls.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 12800,
    location: "Queenstown, Otago",
    country: "New Zealand",
    category: "Adventure",
    geometry: { lat: -45.0312, lng: 168.6626 },
    amenities: ["Lake & Mountain View", "Cedar Hot Tub", "Ski Storage Room", "Indoor Fireplace", "High-speed Wifi", "BBQ Patio"],
    rating: 4.94,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 3,
    aiSummary: {
      positives: ["Unreal mountain vistas over the lake", "Hot tub after a day of adventures", "Super modern designer finishes"],
      negatives: ["Steep driveway; 4WD recommended in heavy winter"],
      overall: "The ultimate adventure headquarters in New Zealand's adrenaline capital.",
      sentiment: 94,
      updatedAt: new Date(),
    },
  },
  {
    title: "Manhattan Skyline Penthouse & Private Terrace",
    description:
      "Sun-drenched duplex penthouse in trendy SoHo featuring 14-foot timber-beamed ceilings, private landscaped rooftop terrace with skyline views, gourmet chef kitchen, wood-burning brick fireplace, and designer art installations.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 17500,
    location: "SoHo, New York City",
    country: "United States",
    category: "City",
    geometry: { lat: 40.7233, lng: -74.0030 },
    amenities: ["Private Rooftop Terrace", "Chef Kitchen", "Skyline Views", "Doorman Building", "Gym Access", "High-speed Wifi"],
    rating: 4.93,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    aiSummary: {
      positives: ["Stunning sunset views of Manhattan skyline", "Prime SoHo location near top restaurants", "Spacious layout by NYC standards"],
      negatives: ["City street sounds occasionally reach terrace"],
      overall: "Chic metropolitan luxury in the heartbeat of downtown Manhattan.",
      sentiment: 93,
      updatedAt: new Date(),
    },
  },
  {
    title: "Rolling Hills 16th-Century Tuscan Farmhouse",
    description:
      "Surrounded by centuries-old olive groves and Sangiovese vineyards in the Chianti countryside. Boasts terracotta vaulted ceilings, rustic stone chef kitchen, private saltwater infinity swimming pool, and wine cellar tastings.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 8800,
    location: "Chianti, Tuscany",
    country: "Italy",
    category: "Farm",
    geometry: { lat: 43.5855, lng: 11.3150 },
    amenities: ["Saltwater Pool", "Vineyard View", "Wine Cellar", "Outdoor Dining Pergola", "Fireplace", "High-speed Wifi"],
    rating: 4.96,
    guests: 8,
    bedrooms: 4,
    beds: 5,
    baths: 3,
    aiSummary: {
      positives: ["Idyllic rolling hill vistas", "Fresh estate olive oil and wine", "Tranquil country atmosphere"],
      negatives: ["Car is essential for exploring nearby villages"],
      overall: "A postcard Tuscan dream with rustic elegance and exceptional wines.",
      sentiment: 96,
      updatedAt: new Date(),
    },
  },
  {
    title: "Overwater Turquoise Lagoon Villa with Private Slide",
    description:
      "An idyllic overwater villa perched directly over shimmering turquoise reefs in Baa Atoll. Features a private curved water slide plunging into the ocean, glass floor viewing panel, outdoor rain shower, and dedicated island concierge.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 26000,
    location: "Baa Atoll, Maldives",
    country: "Maldives",
    category: "Luxury",
    geometry: { lat: 5.1218, lng: 73.0118 },
    amenities: ["Lagoon Water Slide", "Glass Floor Panel", "Private Sunset Deck", "Infinity Plunge Pool", "Speedboat Transfer", "Wifi"],
    rating: 5.0,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 2,
    aiSummary: {
      positives: ["Slide into the turquoise ocean is pure joy", "Manta rays swimming under glass floor", "Absolute paradise luxury"],
      negatives: ["Seaplane transfer required to reach atoll"],
      overall: "The ultimate tropical indulgence on earth with flawless service.",
      sentiment: 100,
      updatedAt: new Date(),
    },
  },
  {
    title: "Shinjuku Sky Penthouse & Neon View Balcony",
    description:
      "Towering high above the vibrant streets of Shinjuku, this sleek designer apartment offers cinematic views of Tokyo's neon skyline, high-tech smart home amenities, Japanese deep-soaking bath, and direct elevator access.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 9500,
    location: "Shinjuku, Tokyo",
    country: "Japan",
    category: "City",
    geometry: { lat: 35.6938, lng: 139.7034 },
    amenities: ["Neon Skyline View", "Smart Home Controls", "Ofuro Soaking Tub", "High-speed Wifi", "Air Conditioning", "Coffee Bar"],
    rating: 4.92,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    aiSummary: {
      positives: ["Spectacular night views of Tokyo", "Ultra-fast wifi and smart controls", "Steps from Shinjuku station"],
      negatives: ["Busy neighborhood, though apartment is soundproofed"],
      overall: "Modern Tokyo living at its finest, offering unmatched convenience and skyline views.",
      sentiment: 93,
      updatedAt: new Date(),
    },
  },
  {
    title: "Lochside Baronnial Stone Castle Tower",
    description:
      "A grand 15th-century stone tower set on the mist-shrouded shores of the Scottish Highlands. Features spiral stone staircases, roaring banquet fireplaces, four-poster canopied beds, antique armory library, and private highland boat dock.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 15500,
    location: "Inverness, Scottish Highlands",
    country: "United Kingdom",
    category: "Castle",
    geometry: { lat: 57.3229, lng: -4.4244 },
    amenities: ["Historic Stone Tower", "Loch View", "Grand Fireplace", "Library", "Free Parking", "High-speed Wifi"],
    rating: 4.95,
    guests: 8,
    bedrooms: 4,
    beds: 4,
    baths: 4,
    aiSummary: {
      positives: ["Living inside real Scottish history", "Atmospheric fireplaces & loch views", "Warm highland hospitality"],
      negatives: ["Thick stone walls mean wifi strongest in library"],
      overall: "An epic castle stay straight out of a Scottish fairy tale.",
      sentiment: 95,
      updatedAt: new Date(),
    },
  },
  {
    title: "Snowmass Ski Chalet with Hot Tub & Pine Views",
    description:
      "Exclusive mountain lodge offering ski-in/ski-out access onto Aspen Snowmass slopes. Relax in an outdoor sunken hot tub beneath pine boughs, gather around the massive river-rock fireplace, or cook in the professional Viking kitchen.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 21000,
    location: "Aspen, Colorado",
    country: "United States",
    category: "Mountains",
    geometry: { lat: 39.1911, lng: -106.8175 },
    amenities: ["Ski-in / Ski-out", "Outdoor Hot Tub", "Heated Driveway", "Chef Kitchen", "River Rock Fireplace", "Wifi"],
    rating: 4.97,
    guests: 10,
    bedrooms: 5,
    beds: 6,
    baths: 5,
    aiSummary: {
      positives: ["Direct ski access onto world-class slopes", "Hot tub surrounded by fresh snow", "Spacious and immaculate lodge"],
      negatives: ["Premium pricing during peak holiday weeks"],
      overall: "A masterclass in American mountain luxury for family and group ski trips.",
      sentiment: 97,
      updatedAt: new Date(),
    },
  },
  {
    title: "Great Migration Canvas Safari Camp",
    description:
      "Eco-luxury canvas tented suite pitched directly along the migration paths of the Serengeti. Features handcrafted mahogany furnishings, en-suite bush showers, sundowner gin & tonics by the campfire, and twice-daily guided 4x4 game drives.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 18000,
    location: "Serengeti National Park",
    country: "Tanzania",
    category: "Adventure",
    geometry: { lat: -2.3333, lng: 34.8333 },
    amenities: ["Safari Game Drives", "Bush Dining", "Wildlife Viewing", "Campfire", "En-suite Bath", "All Meals Included"],
    rating: 4.99,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    aiSummary: {
      positives: ["Saw lions and elephants from our deck", "Remarkable safari guides", "Fabulous gourmet food in the bush"],
      negatives: ["Solar power managed during deep night"],
      overall: "A mesmerizing and profound African wilderness journey.",
      sentiment: 99,
      updatedAt: new Date(),
    },
  },
  {
    title: "Pinecrest Waterfront Cabin with Private Pier",
    description:
      "Perched on the crystal-clear shores of Lake Tahoe among towering sugar pines. Includes a private deep-water boat dock, wrap-around cedar sundeck with outdoor gas barbecue, granite wood fireplace, and kayaks for sunrise paddling.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 8400,
    location: "Lake Tahoe, California",
    country: "United States",
    category: "Lake",
    geometry: { lat: 39.0968, lng: -120.0324 },
    amenities: ["Private Pier & Dock", "Wrap-around Deck", "Granite Fireplace", "BBQ Grill", "Kayaks Included", "Wifi"],
    rating: 4.93,
    guests: 6,
    bedrooms: 3,
    beds: 4,
    baths: 2,
    aiSummary: {
      positives: ["Crystal clear water right off private dock", "Paddling kayaks in the calm morning", "Very cozy cabin feel"],
      negatives: ["Summer boat traffic on weekends"],
      overall: "Classic California lake living with unbeatable water access.",
      sentiment: 94,
      updatedAt: new Date(),
    },
  },
  {
    title: "Rainforest Canopy Treehouse & Ocean View",
    description:
      "Suspended 40 feet in the lush jungle canopy overlooking the Pacific Ocean in Manuel Antonio. Watch toucans, sloths, and capuchin monkeys from your open-air hammock deck, followed by a quick 10-minute rainforest walk down to private beaches.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 6200,
    location: "Manuel Antonio, Puntarenas",
    country: "Costa Rica",
    category: "Forest",
    geometry: { lat: 9.3904, lng: -84.1485 },
    amenities: ["Canopy Ocean View", "Wildlife Watching", "Eco Solar Powered", "Hammock Deck", "Wifi", "Free Parking"],
    rating: 4.92,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    aiSummary: {
      positives: ["Monkeys and sloths seen daily in the trees", "Spectacular ocean views from the hammock", "Immersion in nature"],
      negatives: ["Short uphill walk through rainforest path"],
      overall: "An eco-paradise that connects you intimately with Costa Rican wildlife.",
      sentiment: 93,
      updatedAt: new Date(),
    },
  },
  {
    title: "Erg Chebbi Desert Luxury Berber Camp",
    description:
      "Set amidst the golden 150-meter sand dunes of the Sahara in Merzouga. Features private en-suite royal tents with handcrafted Berber textiles, sunset camel caravan treks, fireside live desert folk music, and breathtaking stargazing.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 4800,
    location: "Merzouga, Sahara",
    country: "Morocco",
    category: "Desert",
    geometry: { lat: 31.1444, lng: -4.0197 },
    amenities: ["Camel Trek Included", "Campfire & Folk Music", "Moroccan Tajine Dinner", "Stargazing", "Private Bath"],
    rating: 4.94,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    aiSummary: {
      positives: ["Unbelievable silence and stars of the Sahara", "Delicious authentic tajines", "Enchanting Berber drums by the fire"],
      negatives: ["Desert heat in midday; tents well ventilated"],
      overall: "A spiritual and romantic journey across the timeless Sahara dunes.",
      sentiment: 95,
      updatedAt: new Date(),
    },
  },
  {
    title: "Secluded Beachfront Villa with Infinity Pool",
    description:
      "Tucked away on the secluded south shore of Mykonos, this minimalist white-and-stone villa features an infinity pool blending seamlessly into the Aegean, private sunbeds, outdoor marble dining pavilion, and sheltered sunset views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 16500,
    location: "Mykonos, Cyclades",
    country: "Greece",
    category: "Beach",
    geometry: { lat: 37.4467, lng: 25.3289 },
    amenities: ["Infinity Pool", "Sea View", "Sunbeds", "Air Conditioning", "High-speed Wifi", "Free Parking", "BBQ"],
    rating: 4.95,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 3,
    aiSummary: {
      positives: ["Stunning sunset views over the bay", "Absolute privacy yet close to town", "Spotless and modern design"],
      negatives: ["Windy on certain summer afternoons"],
      overall: "A quintessential Cycladic summer luxury villa.",
      sentiment: 95,
      updatedAt: new Date(),
    },
  },
  {
    title: "Lakeside Log Cabin in the White Mountains",
    description:
      "Spend your days fishing, paddleboarding, and relaxing in this cozy timber cabin set beside a quiet glacial lake in New Hampshire. Features a stone fireplace, wood deck over the water, and vibrant autumn foliage views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 4900,
    location: "White Mountains, New Hampshire",
    country: "United States",
    category: "Lake",
    geometry: { lat: 44.2706, lng: -71.3033 },
    amenities: ["Lakeside Dock", "Stone Fireplace", "Paddleboard Included", "Wifi", "BBQ Grill", "Free Parking"],
    rating: 4.89,
    guests: 5,
    bedrooms: 2,
    beds: 3,
    baths: 1,
    aiSummary: {
      positives: ["Peaceful lake without motorboats", "Stunning fall foliage reflections", "Cozy cabin atmosphere"],
      negatives: ["Limited cell reception, good wifi inside"],
      overall: "The ideal peaceful mountain lake getaway for families and couples.",
      sentiment: 92,
      updatedAt: new Date(),
    },
  },
  {
    title: "Organic Vineyard Farmhouse with Olive Mill",
    description:
      "Stay on a functioning certified organic vineyard and olive mill in the French countryside. Walk among blooming lavender fields, sample cold-pressed extra virgin olive oil, and relax beneath shade pergolas with local goat cheeses.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 6100,
    location: "Provence, Luberon",
    country: "France",
    category: "Farm",
    geometry: { lat: 43.8824, lng: 5.2348 },
    amenities: ["Vineyard Walk", "Organic Olive Oil Tasting", "Pergola Dining", "Pool", "Wifi", "Free Parking"],
    rating: 4.91,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 2,
    aiSummary: {
      positives: ["Picturesque lavender and olive trees", "Generous host with fresh produce", "Quiet French village setting"],
      negatives: ["Pool is unheated in late autumn"],
      overall: "A restorative pastoral retreat in the sunlit heart of Provence.",
      sentiment: 93,
      updatedAt: new Date(),
    },
  },
  {
    title: "Historic Medieval Castle Watchtower & Moat",
    description:
      "Ascend the spiral ramparts of a fortified 14th-century castle tower overlooking the Dordogne river. Featuring authentic stone arrow-slit windows, antique oak dining tables, a library of antique maps, and evening torchlit courtyard walks.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 13900,
    location: "Dordogne Valley, Nouvelle-Aquitaine",
    country: "France",
    category: "Castle",
    geometry: { lat: 44.8211, lng: 1.1719 },
    amenities: ["Historic Ramparts", "Moat & Courtyard", "Grand Fireplace", "Library", "Free Parking", "Wifi"],
    rating: 4.96,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 3,
    aiSummary: {
      positives: ["True medieval experience with modern comfort", "Dramatic valley views from battlements", "Unique and memorable stay"],
      negatives: ["Many spiral steps up to tower rooms"],
      overall: "An extraordinary historical experience in the cradle of medieval France.",
      sentiment: 96,
      updatedAt: new Date(),
    },
  },
  {
    title: "Glacier Bay Floating Arctic Eco Cabin",
    description:
      "Perched in a sheltered Arctic fjord surrounded by dramatic glaciers and snowfields. Features solar and hydro heating, floor-to-ceiling triple-glazed viewing glass for spotting seals and whales, and sauna access.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    },
    price: 12500,
    location: "Tromso, Arctic Circle",
    country: "Norway",
    category: "Arctic",
    geometry: { lat: 69.6492, lng: 18.9553 },
    amenities: ["Fjord View", "Arctic Sauna", "Whale Watching Deck", "Heated Floors", "High-speed Wifi", "Breakfast Included"],
    rating: 4.97,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    aiSummary: {
      positives: ["Saw whales right from the living room", "Amazing sauna followed by Arctic dip", "Cozy and ultra-warm inside"],
      negatives: ["Midnight sun in summer or polar night in winter"],
      overall: "A serene Arctic sanctuary at the very edge of the world.",
      sentiment: 97,
      updatedAt: new Date(),
    },
  }
];

module.exports = { data: sampleListings };